### ISSUE TITLE
 fitMeanVarCurve error 

### ISSUE THREAD

**Issue by tan5251** [tushiqi/MAnorm2#2]
library(MAnorm2)
data <- read.table("D:\\12-8/1-7/epic/MAnorm2/epiccallpeak_0.05_h3k_profile_bins.xls",header = T)
norm <- normalize(data, count = 6:7, occupancy = 12:13)
norm <- normalize(norm, count = 8:9, occupancy = 14:15)
conds <- list(d65 = bioCond(norm[6:7], norm[12:13], name = "d65"),d90 = bioCond(norm[8:9], norm[14:15], name = "d90"))
conds <- normBioCond(conds
conds <- fitMeanVarCurve(conds, method = "parametric", occupy.only = TRUE,init.coef = c(0.1, 10))

During the parametric fit procedure:
After iteration 1: coef = (0.0821818, 2.01018); 1361 (0.78%) outlier(s) detected
After iteration 2: coef = (0.0497606, 2.1688); 1439 (0.82%) outlier(s) detected
After iteration 3: coef = (0.0276251, 2.63155); 1388 (0.79%) outlier(s) detected
After iteration 4: coef = (0.0131094, 2.95489); 1379 (0.79%) outlier(s) detected
After iteration 5: coef = (0.00597452, 3.119); 1418 (0.81%) outlier(s) detected
After iteration 6: coef = (0.00337247, 3.17739); 1420 (0.81%) outlier(s) detected
After iteration 7: coef = (0.00145952, 3.1951); 1439 (0.82%) outlier(s) detected
After iteration 8: coef = (0.000429077, 3.24471); 1451 (0.83%) outlier(s) detected
After iteration 9: coef = (6.32897e-05, 3.25055); 1459 (0.83%) outlier(s) detected
After iteration 10: coef = (0.000623793, 3.23509); 1450 (0.83%) outlier(s) detected
After iteration 11: coef = (0.000624391, 3.23728); 1449 (0.83%) outlier(s) detected
After iteration 12: coef = (0.00129248, 3.22126); 1438 (0.82%) outlier(s) detected
After iteration 13: coef = (0.000451543, 3.24328); 1451 (0.83%) outlier(s) detected
After iteration 14: coef = (0.000940307, 3.22948); 1441 (0.82%) outlier(s) detected
After iteration 15: coef = (0.00266528, 3.1899); 1427 (0.82%) outlier(s) detected
After iteration 16: coef = (0.000354502, 3.24825); 1450 (0.83%) outlier(s) detected
After iteration 17: coef = (0.000917505, 3.23022); 1441 (0.82%) outlier(s) detected
After iteration 18: coef = (0.00239003, 3.19667); 1431 (0.82%) outlier(s) detected
After iteration 19: coef = (0.00504742, 3.13537); 1420 (0.81%) outlier(s) detected
After iteration 20: coef = (0.00144397, 3.2225); 1430 (0.82%) outlier(s) detected
After iteration 21: coef = (6.27676e-05, 3.2536); 1458 (0.83%) outlier(s) detected
After iteration 22: coef = (0.000623851, 3.23535); 1450 (0.83%) outlier(s) detected
After iteration 23: coef = (0.000624447, 3.23728); 1449 (0.83%) outlier(s) detected
After iteration 24: coef = (0.00133988, 3.2201); 1436 (0.82%) outlier(s) detected
After iteration 25: coef = (0.000587136, 3.24076); 1450 (0.83%) outlier(s) detected
After iteration 26: coef = (0.000538113, 3.23912); 1450 (0.83%) outlier(s) detected
Converged.

There were 50 or more warnings (use warnings() to see the first 50)
1: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
2: step size truncated due to divergence
3: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
4: step size truncated due to divergence
5: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
6: step size truncated due to divergence
7: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
8: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
9: step size truncated due to divergence
10: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
11: step size truncated due to divergence
12: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
13: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
14: step size truncated due to divergence
15: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
16: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
17: step size truncated due to divergence
18: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
19: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
20: step size truncated due to divergence
21: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
22: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
23: step size truncated due to divergence
24: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
25: glm.fit: algorithm did not converge
26: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
27: step size truncated due to divergence
28: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
29: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
30: step size truncated due to divergence
31: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
32: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
33: step size truncated due to divergence
34: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
35: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
36: step size truncated due to divergence
37: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
38: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
39: step size truncated due to divergence
40: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
41: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
42: step size truncated due to divergence
43: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
44: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
45: step size truncated due to divergence
46: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
47: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
48: step size truncated due to divergence
49: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs
50: In log(ifelse(y == 0, 1, y/mu)) : 产生了NaNs

Do these warning will affect the final results?
why the warnings occur?
Thanks advance!

**Comment by tushiqi** [comment]
@tan5251 

Intrinsically, the parametric regression method applies a GLM (generalized linear model) fitting procedure to the mean-variance trend. Technically, this procedure uses an iteration scheme for the associated parameter estimation (refer to https://en.wikipedia.org/wiki/Generalized_linear_model#Maximum_likelihood and also the R documentation for the function **glm()** for details). The warning messages suggest that the iteration scheme does not converge smoothly. This is usually because the mean-variance trend is not very consistent with the used parametric formula, and I have encountered these warning messages in practical data analysis as well.

My experience is that these warnings will not essentially affect the final analysis results, but I still recommend using the **plotMeanVarCurve()** function to visualize the fitting results. Besides, please check the number of prior degrees of freedom by **summary(conds[[1]])**. It should be large (e.g., >9) if each **bioCond** consists of biological replicates.

**Comment by tan5251** [comment]
I am very grateful for your help. To be honest, i do not understand very well for your normalization method although i had read several times. I am very sorry about that. Here it is the  results of code "summary(conds[[]])".  The number of prior degrees of freedom is Inf. Is it seems  normal? One more question is that the number of gene with the threshold value (P.adj < 0.05  & |Mval| >1 ) is very small in my final results, which  is far away from my expectation. Please help me to take a look for the results of  summary(conds[[]]). Thanks a lot !

 > summary(conds[[1]])

Biological condition d65:
182773 genomic intervals with 2 profiles

Occupancy states:
84769 (46.4%) of the genomic intervals occupied by the condition

Summary of mean signal intensities at the genomic intervals:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-0.9456  3.6397  4.1353  4.0572  4.5369 15.7142 

Summary of standard deviations of signal intensities at the genomic intervals:
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
0.000338 0.132578 0.283044 0.378709 0.506578 8.497645 

The genomic intervals are associated with the same structure matrix:
              d652.read_cnt d653.read_cnt
d652.read_cnt             1             0
d653.read_cnt             0             1

Function call for associating a mean-variance curve with the condition:
   fitMeanVarCurve(conds = conds, method = "parametric", occupy.only = TRUE, 
    init.coef = c(0.1, 10))

Summary of the mean-variance curve:
Fit method = "parametric fit"
ID = "2021-01-19 15:14:40 3F4B49YQE9"
Number of prior dfs = Inf
Variance ratio factor = 1.69

> summary(conds[[2]])

Biological condition d90:
182773 genomic intervals with 2 profiles

Occupancy states:
90170 (49.3%) of the genomic intervals occupied by the condition

Summary of mean signal intensities at the genomic intervals:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -1.097   3.571   4.114   4.022   4.544  14.845 

Summary of standard deviations of signal intensities at the genomic intervals:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
0.00003 0.11425 0.24046 0.31234 0.42978 5.65234 

The genomic intervals are associated with the same structure matrix:
              d901.read_cnt d903.read_cnt
d901.read_cnt             1             0
d903.read_cnt             0             1

Function call for associating a mean-variance curve with the condition:
   fitMeanVarCurve(conds = conds, method = "parametric", occupy.only = TRUE, 
    init.coef = c(0.1, 10))

Summary of the mean-variance curve:
Fit method = "parametric fit"
ID = "2021-01-19 15:14:40 3F4B49YQE9"
Number of prior dfs = Inf
Variance ratio factor = 1.05

**Comment by tushiqi** [comment]
@tan5251 

This is perfectly normal. Having **Inf** prior degrees of freedom means that your replicates are associated with a high reproducibility and the experiment system is very stable.

For the issue of a small number of significant intervals, I notice the occupancy ratios of the two **bioCond**s are small (46.4% and 49.3%). Is it because of the existence of other samples in your data set (a large number of intervals may be involved because of the peaks identified for these samples)? Also, the total 182773 genomic intervals seem too many, and you may want to apply a more stringent cutoff for peak calling. In any case, I suggest that you remove the intervals not occupied by either **bioCond** and re-adjust the _p_-values (see ?diffTest). Try also a smaller cutoff for |Mval| (e.g., **log2(1.5)**).

For a detailed description of the methodology, please refer to https://genome.cshlp.org/content/31/1/131.

**Comment by tan5251** [comment]
Thanks a lot for your help. I did made a error that apply additional samples into data sets, which resulted in low occupancy ratios of the two bioConds. Now the occupancy ratios were up to 70 to 80% and the number of significant interval increased too. I am very grateful for you suggestions. I  have another qusetion about typical bins size. My ChIP-seq data is H3K27me3 modificaiton, a typcial broad domain. The median of peak length is  3kb in my data. Should i increase the typical bins size to 3kb or more ?

**Comment by tushiqi** [comment]
@tan5251 

You are very welcome.

Yes, using the median peak length as the bin size is a safe way for practical data analysis, and I believe in your case using 3kb makes sense.

**Comment by tan5251** [comment]
I get it. Thanks for your reply.
