### ISSUE TITLE
Multi variable analysis

### ISSUE THREAD

**Issue by jeffpkamp** [tushiqi/MAnorm2#4]
This isn't really an issue, but I wanted to know if MAnorm2 was capable of multi-variant analysis in the same way DESeq2 is.  For example, if we wanted to remove the effects of a "condition" vs the "group" in DESeq2 we would use the design `~ group + condition`.  Is there anything like that for MAnorm2?

**Comment by tushiqi** [comment]
@jeffpkamp 

This is definitely a good point. I must admit, however, that the current version of MAnorm2 cannot handle arbitrary model formulas (or design matrices). More specifically, the current MAnorm2 can only be used for comparisons between two or more groups of samples (as in two-sample _t_-test or ANOVA).

I have been trying to implement the functionality you proposed. Once I achieve it, I’ll upgrade MAnorm2 and point it out in the [inst/NEWS](https://github.com/tushiqi/MAnorm2/blob/master/inst/NEWS) file.
